<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels = array();

// preferences			  
$labels['default_view'] = 'Vista predeterminada';
$labels['time_format'] = 'Formato de tiempo';
$labels['timeslots'] = 'Los intervalos de tiempo por hora';
$labels['first_day'] = 'Primer d&amp;iacute;a de la semana';
$labels['first_hour'] = 'Primera hora para mostrar';
$labels['workinghours'] = 'Horas laborales';
$labels['add_category'] = 'A&amp;ntilde;adir categor&amp;iacute;a';
$labels['remove_category'] = 'Borrar la categor&amp;iacute;a';
$labels['defaultcalendar'] = 'Crear nuevos eventos en';
$labels['eventcoloring'] = 'Evento para colorear';
$labels['coloringmode0'] = 'De acuerdo con el calendario';
$labels['coloringmode1'] = 'De acuerdo con la categor&amp;iacute;a';
$labels['coloringmode2'] = 'Calendario para el esquema, la categor&amp;iacute;a de contenido';
$labels['coloringmode3'] = 'Calendario para el esquema, la categor&amp;iacute;a de contenido';
$labels['afternothing'] = 'No hacer nada';
$labels['aftertrash'] = 'Mover a la papelera';
$labels['afterdelete'] = 'Eliminar el mensaje';
$labels['afterflagdeleted'] = 'Marcar como eliminado';
$labels['aftermoveto'] = 'Mover a...';
$labels['itipoptions'] = 'Invitaciones para el evento';
$labels['afteraction'] = 'Se procesa despu&amp;eacute;s de un mensaje de invitaci&amp;oacute;n o actualizaci&amp;oacute;n';
// calendar		   
$labels['calendar'] = 'Calendario';
$labels['calendars'] = 'Calendarios';
$labels['category'] = 'Categor&amp;iacute;a';
$labels['categories'] = 'Categor&amp;iacute;as';
$labels['createcalendar'] = 'Crear nuevo calendario';
$labels['editcalendar'] = 'Editar propiedades del calendario';
$labels['name'] = 'Nombre';
$labels['color'] = 'Color';
$labels['day'] = 'D&amp;iacute;a';
$labels['week'] = 'Semana';
$labels['month'] = 'Mes';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nuevo';
$labels['new_event'] = 'Nuevo evento';
$labels['edit_event'] = 'Editar evento';
$labels['edit'] = 'Editar';
$labels['save'] = 'Guardar';
$labels['removelist'] = 'Borrar de la lista';
$labels['cancel'] = 'Cancelar';
$labels['select'] = 'Seleccionar';
$labels['print'] = 'Imprimir';
$labels['printtitle'] = 'Imprimir calendarios';
$labels['title'] = 'Resumen';
$labels['description'] = 'Descripci&amp;oacute;n';
$labels['all-day'] = 'Todo el d&amp;iacute;a';
$labels['export'] = 'Exportar';
$labels['exporttitle'] = 'Exportar a iCalendar';
$labels['exportrange'] = 'Eventos de';
$labels['exportattachments'] = 'con los adjuntos';
$labels['customdate'] = 'Fecha personalizada';
$labels['location'] = 'Ubicaci&amp;oacute;n';
$labels['url'] = 'URL';
$labels['date'] = 'Fecha';
$labels['start'] = 'Inicio';
$labels['starttime'] = 'Tiempo de inicio';
$labels['end'] = 'Fin';
$labels['endtime'] = 'Hora de finalizaci&amp;oacute;n';
$labels['repeat'] = 'Repetir';
$labels['selectdate'] = 'Seleccione la fecha';
$labels['freebusy'] = 'Mostrarme como';
$labels['free'] = 'Disponible';
$labels['busy'] = 'Ocupado';
$labels['outofoffice'] = 'Fuera de la oficina';
$labels['tentative'] = 'Provisional';
$labels['mystatus'] = 'Mi estado';
$labels['status'] = 'Estado';
$labels['status-confirmed'] = 'Confirmado';
$labels['status-cancelled'] = 'Cancelado';
$labels['priority'] = 'Prioridad';
$labels['sensitivity'] = 'Privacidad';
$labels['public'] = 'P&amp;uacute;blica';
$labels['private'] = 'Privada';
$labels['confidential'] = 'Confidencial';
$labels['links'] = 'Referencia';
$labels['alarms'] = 'Recordatorio';
$labels['comment'] = 'Comentario';
$labels['created'] = 'Creado';
$labels['changed'] = '&amp;Uacute;ltima modificaci&amp;oacute;n';
$labels['unknown'] = 'Desconocido';
$labels['eventoptions'] = 'Opciones';
$labels['generated'] = 'Creado a las';
$labels['eventhistory'] = 'Historial';
$labels['removelink'] = 'Eliminar la referencia de correo electr&amp;oacute;nico';
$labels['printdescriptions'] = 'Imprimir descripci&amp;oacute;n ';
$labels['parentcalendar'] = 'Inserte en el interior';
$labels['searchearlierdates'] = '&amp;laquo; B&amp;uacute;squeda de eventos anteriores';
$labels['searchlaterdates'] = 'B&amp;uacute;squeda de eventos posteriores  &amp;raquo;';
$labels['andnmore'] = '$nr m&amp;aacute;s...';
$labels['togglerole'] = 'Haga clic para cambiar el rol';
$labels['createfrommail'] = 'Guardar como evento';
$labels['importevents'] = 'Importar eventos';
$labels['importrange'] = 'Eventos de';
$labels['onemonthback'] = '1 mes atr&amp;aacute;s';
$labels['nmonthsback'] = '$nr meses atr&amp;aacute;s';
$labels['showurl'] = 'Mostrar URL del calendario';
$labels['showurldescription'] = 'Usar la siguiente direcci&amp;oacute;n para acceder (s&amp;oacute;lo lectura) en su calendario desde otras aplicaciones. Puede copiar y pegar esto en cualquier software de calendario que admita el formato iCal.';
$labels['caldavurldescription'] = 'Copie esta direcci&amp;oacute;n en un &amp;lt;a href=&amp;quot;http://en.wikipedia.org/wiki/CalDAV&amp;quot; target=&amp;quot;_blank&amp;quot;&amp;gt;CalDAV&amp;lt;/a&amp;gt; cliente (Evolution o Mozilla Thunderbird) para sincronizar esta tarea con su ordenador o celular.';
$labels['findcalendars'] = 'Buscar calendarios ...';
$labels['searchterms'] = 'Buscar t&amp;eacute;rminos';
$labels['calsearchresults'] = 'Calendarios disponibles';
$labels['calendarsubscribe'] = 'Lista Permanente';
$labels['nocalendarsfound'] = 'No se han encontrado calendarios';
$labels['nrcalendarsfound'] = '$nr calendarios encontrados';
$labels['quickview'] = 'Ver solo este calendario';
$labels['invitationspending'] = 'Invitaciones pendientes';
$labels['invitationsdeclined'] = 'Invitaciones rechazada';
$labels['changepartstat'] = 'Cambiar el estado del participante';
$labels['rsvpcomment'] = 'Texto de la invitaci&amp;oacute;n';
// agenda view			  
$labels['listrange'] = 'Rango de visualizaci&amp;oacute;n:';
$labels['listsections'] = 'Dividir en:';
$labels['smartsections'] = 'Secciones inteligentes';
$labels['until'] = 'hasta';
$labels['today'] = 'Hoy';
$labels['tomorrow'] = 'Ma&amp;ntilde;ana';
$labels['thisweek'] = 'Esta semana';
$labels['nextweek'] = 'Pr&amp;oacute;xima semana';
$labels['prevweek'] = 'Semana pasada';
$labels['thismonth'] = 'Este mes';
$labels['nextmonth'] = 'Pr&amp;oacute;ximo mes';
$labels['weekofyear'] = 'Semana';
$labels['pastevents'] = 'Pasado';
$labels['futureevents'] = 'Futuro';
// alarm/reminder settings						  
$labels['showalarms'] = 'Mostrar recordatorios';
$labels['defaultalarmtype'] = 'Configuraci&amp;oacute;n predeterminada del recordatorio';
$labels['defaultalarmoffset'] = 'Tiempo de aviso predeterminado';
// attendees			
$labels['attendee'] = 'Participante';
$labels['role'] = 'Rol';
$labels['availability'] = 'Disponible';
$labels['confirmstate'] = 'Estado';
$labels['addattendee'] = 'A&amp;ntilde;ada participante';
$labels['roleorganizer'] = 'Organizador';
$labels['rolerequired'] = 'Requerido';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Silla';
$labels['rolenonparticipant'] = 'Ausente';
$labels['cutypeindividual'] = 'Individual';
$labels['cutypegroup'] = 'Grupo';
$labels['cutyperesource'] = 'Recurso';
$labels['cutyperoom'] = 'Habitaci&amp;oacute;n';
$labels['availfree'] = 'Disponible';
$labels['availbusy'] = 'Ocupado';
$labels['availunknown'] = 'Desconocido';
$labels['availtentative'] = 'Provisional';
$labels['availoutofoffice'] = 'Fuera de la oficina';
$labels['delegatedto'] = 'Delegar a: ';
$labels['delegatedfrom'] = 'Delegado de:';
$labels['scheduletime'] = 'Buscar disponibilidad';
$labels['sendinvitations'] = 'Enviar invitaciones';
$labels['sendnotifications'] = 'Notificar a los participantes acerca de las modificaciones';
$labels['sendcancellation'] = 'Notificar a los participantes sobre la cancelaci&amp;oacute;n de eventos';
$labels['onlyworkinghours'] = 'Encuentra disponibilidad dentro de mis horas de trabajo';
$labels['reqallattendees'] = 'Requeridos/todos los participantes';
$labels['prevslot'] = 'Ranura anterior';
$labels['nextslot'] = 'Siguiente ranura';
$labels['suggestedslot'] = 'Ranura sugerida';
$labels['noslotfound'] = 'Incapaz de encontrar un intervalo de tiempo libre';
$labels['invitationsubject'] = 'Usted  sido invitado a &amp;quot;$title&amp;quot;';
$labels['invitationmailbody'] = &amp;quot;*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nSe adjunta un archivo iCalendar con todos los detalles del evento que se puede importar a la aplicaci&amp;oacute;n de calendario.&amp;quot;;
$labels['invitationattendlinks'] = &amp;quot;En caso de que su cliente de correo electr&amp;oacute;nico no admite solicitudes iTIP que puede utilizar el siguiente enlace para aceptar o rechazar esta invitaci&amp;oacute;n:\n\$url&amp;quot;;
$labels['eventupdatesubject'] = '&amp;quot;$title&amp;quot; Ha sido actualizado';
$labels['eventupdatesubjectempty'] = 'Un evento que le concierne ha sido actualizado';
$labels['eventupdatemailbody'] = &amp;quot;*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nSe adjunta un archivo iCalendar con los detalles del evento actualizados que se puede importar a la aplicaci&amp;oacute;n de calendario.&amp;quot;;
$labels['eventcancelsubject'] = '&amp;quot;$title&amp;quot; has been cancelled';															  
$labels['eventcancelmailbody'] = &amp;quot;*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nEl evento ha sido cancelado por\$organizer.\n\nSe adjunta un archivo iCalendar con los detalles del evento actualizados.&amp;quot;;
// invitation handling (overrides labels from libcalendaring)															 
$labels['itipobjectnotfound'] = 'El evento referido por este mensaje no se encontr&amp;oacute; en su calendario.';
$labels['itipmailbodyaccepted'] = &amp;quot;\$sender ha aceptado la invitaci&amp;oacute;n al evento siguiente:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees&amp;quot;;
$labels['itipmailbodytentative'] = &amp;quot;\$sender ha aceptado provisionalmente la invitaci&amp;oacute;n al evento siguiente:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees&amp;quot;;
$labels['itipmailbodydeclined'] = &amp;quot;\$sender ha declinado la invitaci&amp;oacute;n al evento siguiente:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees&amp;quot;;
$labels['itipmailbodycancel'] = &amp;quot;\$sender ha rechazado su participaci&amp;oacute;n en el evento siguiente:\n\n*\$title*\n\nWhen: \$date&amp;quot;;
$labels['itipmailbodydelegated'] = &amp;quot;\$sender ha delegado la participaci&amp;oacute;n en el evento siguiente:\n\n*\$title*\n\nWhen: \$date&amp;quot;;
$labels['itipmailbodydelegatedto'] = &amp;quot;\$sender ha delegado la participaci&amp;oacute;n en el siguiente evento a usted:\n\n*\$title*\n\nWhen: \$date&amp;quot;;
$labels['itipdeclineevent'] = '&amp;iquest;Quieres rechazar la invitaci&amp;oacute;n a este evento?';
$labels['declinedeleteconfirm'] = '&amp;iquest;Usted tambi&amp;eacute;n desea eliminar este declinado evento del calendario?';
$labels['itipcomment'] = 'A&amp;ntilde;adir comentarios a la Invitaci&amp;oacute;n/notificaci&amp;oacute;n';
$labels['itipcommenttitle'] = 'Este comentario se adjunta al mensaje de invitaci&amp;oacute;n/notificaci&amp;oacute;n enviada a los participantes';

$labels['notanattendee'] = 'Usted no est&amp;aacute; en la lista como un asistente de este evento';
$labels['eventcancelled'] = 'El evento ha sido cancelado';
$labels['saveincalendar'] = 'guardar en';
$labels['updatemycopy'] = 'Actualizar en mi calendario';
$labels['savetocalendar'] = 'Guardar en mi calendario';
$labels['openpreview'] = 'Comprobar calendario';
$labels['noearlierevents'] = 'Sin eventos anteriores';
$labels['nolaterevents'] = 'Sin eventos posteriores';														   							  
// resources			
$labels['resource'] = 'Recurso';
$labels['addresource'] = 'Libro de recursos';
$labels['findresources'] = 'Buscar recursos';										 										
$labels['resourcedetails'] = 'Detalles';
$labels['resourceavailability'] = 'Disponibilidad';
$labels['resourceowner'] = 'Propietario';
$labels['resourceadded'] = 'El recurso ha sido a&amp;ntilde;adido a tu evento';												 						   

// event dialog tabs					
$labels['tabsummary'] = 'Sumario';
$labels['tabrecurrence'] = 'Recurrencia ';
$labels['tabattendees'] = 'Participantes';										 
$labels['tabresources'] = 'Recursos';
$labels['tabattachments'] = 'Adjuntos';
$labels['tabsharing'] = 'Compartir';
// messages																		
$labels['deleteobjectconfirm'] = '&amp;iquest;Est&amp;aacute;s seguro que deseas eliminar este evento?';
$labels['deleteventconfirm'] = '&amp;iquest;Est&amp;aacute;s seguro que deseas eliminar este evento?';
$labels['deletecalendarconfirm'] = '&amp;iquest;Est&amp;aacute;s seguro que deseas eliminar este calendario con todos sus eventos?';
$labels['deletecalendarconfirmrecursive'] = '&amp;iquest;Est&amp;aacute;s seguro que deseas eliminar este calendario con todos sus eventos y subcalendarios?';																		  																															
$labels['savingdata'] = 'Guardando datos...';
$labels['attendeupdateesuccess'] = 'Se ha actualizado correctamente el estado del participante';
$labels['errorsaving'] = 'Ha fallado al guardar los cambios.';
$labels['operationfailed'] = 'La operaci&amp;oacute;n solicitada ha fallado.';
$labels['invalideventdates'] = '&amp;iexcl;Datos introducidos no v&amp;aacute;lidos! Por favor compruebalos.';
$labels['invalidcalendarproperties'] = '&amp;iexcl;Propiedades de calendario inv&amp;aacute;lidas! Por favor, introduce un nombre v&amp;aacute;lido.';
$labels['searchnoresults'] = 'No se encuentran eventos en los calendarios seleccionados.';
$labels['successremoval'] = 'El evento ha sido eliminado satisfactoriamente.';
$labels['successrestore'] = 'El evento ha sido restaurado satisfactoriamente.';
$labels['errornotifying'] = 'Fallo al enviar notificaciones del evento a los participantes';
$labels['errorimportingevent'] = 'Fallo al importar el evento';
$labels['importwarningexists'] = 'Ya existe una copia de este evento en tu calendario.';
$labels['newerversionexists'] = '&amp;iexcl;Ya existe una versi&amp;oacute;n mas nueva de este evento! Cancelado.';
$labels['nowritecalendarfound'] = 'No se encuentran calendarios para guardar el evento';
$labels['importedsuccessfully'] = 'El evento ha sido sastifactoriamente en el calendario \'$calendar\'';
$labels['updatedsuccessfully'] = 'El evento ha sido actualizado sastifactoriamente en \'$calendar\'';
$labels['attendeupdateesuccess'] = 'El estado del participante ha sido actualizado sastifactoriamente';
$labels['itipsendsuccess'] = 'Invitacion enviada a los participantes.';
$labels['itipresponseerror'] = 'Fallo al enviar la respuesta a la invitaci&amp;oacute;n del evento';															   
$labels['itipinvalidrequest'] = 'Esta invitaci&amp;oacute;n ya no es v&amp;aacute;lida';
$labels['sentresponseto'] = 'Respuesta de la invitaci&amp;oacute;n enviada satisfactoriamente a $mailto';
$labels['localchangeswarning'] = 'You are about to make changes that will only be reflected on your calendar and not be sent to the organizer of the event.';
$labels['importsuccess'] = 'Importados $nr eventos satisfactoriamente';
$labels['importnone'] = 'No se encontraron eventos para importar';
$labels['importerror'] = 'Ha ocurrido un error mientras se importaba';
$labels['aclnorights'] = 'No tienes derechos administrativos sobre este calendario.';

$labels['changeeventconfirm'] = 'Cambiar evento';
$labels['removeeventconfirm'] = 'Eliminar evento';
$labels['changerecurringeventwarning'] = 'Este es un evento recurrente. Would you like to edit the current event only, this and all future occurences, all occurences or save it as a new event?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['removerecurringallonly'] = 'This is a recurring event. As a participant, you can only delete the entire event with all occurences.';
$labels['currentevent'] = 'Current';																																 		
$labels['futurevents'] = 'Futuro';
$labels['allevents'] = 'Todo';
$labels['saveasnew'] = 'Save as new';

// birthdays calendar
$labels['birthdays'] = 'Cumpleaños';
$labels['birthdayscalendar'] = 'Calendario de cumpleaños';
$labels['displaybirthdayscalendar'] = 'Mostrar calendario de cumpleaños';
$labels['birthdayscalendarsources'] = 'De esta libreta de direcciones';
$labels['birthdayeventtitle'] = 'Cumpleaños de $name';
$labels['birthdayage'] = '$age años';

// history dialog
$labels['objectchangelog'] = 'Cambiar historial';
$labels['objectdiff'] = 'Cambiar de $rev1 a $rev2';
$labels['objectnotfound'] = 'Failed to load event data';
$labels['objectchangelognotavailable'] = 'Change history is not available for this event';
$labels['objectdiffnotavailable'] = 'No hay comparación posible que las revisiones seleccionadas';
$labels['revisionrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';
$labels['objectrestoresuccess'] = 'Revisión $rev restaurado correctamente';
$labels['objectrestoreerror'] = 'No se pudo restaurar la revisión antigua';
// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Event participants list';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Available resources';

?>
